version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
  pgweb:
    image: donnex/pgweb:latest
    command: ["-s", "--bind=0.0.0.0", "--listen=8080", "--host=db", "--user=admin", "--pass=admin", "--db=dev", "--ssl=disable"]
    ports:
      - "8081:8080"
    depends_on:
      - db
  app:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    volumes:
      - .:/go/src/app
    ports:
      - "80:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=dev
      - DB_USER=admin
      - DB_PASS=admin
    depends_on:
      - db
    links:
      - db